# Generated by cucumber-sinatra. (2015-03-31 13:49:32 +0200)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'app/app.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'

Capybara.app = MarsRovers

class MarsRoversWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  MarsRoversWorld.new
end
